# SAMPLES
NUM_SAMPLES: 50
NUM_HIDDEN: 2000

# neural network training hyper parameters
EPOCHS: 5000  #15000  , 5000 for adam optimizer
LEARNING_RATE: 0.001 #0.0001    #0.01 for adam
WEIGHT_DECAY: 0.0001 #0.01,   0.1 for adam
MOMENTUM: 0.999

# Learning rate scheduler parameters
STEP_SIZE: 2000 #5000. 2000 for adam
GAMMA: 0.9

# Scale the data
y_scale: True

VARIANCE: 85